### ISSUE TITLE
Support `zadd`

### ISSUE THREAD

**Issue by trkohler** [sabledb-io/sabledb#15]
[ZADD | Docs](https://redis.io/docs/latest/commands/zadd/)

**Comment by sabledb-io** [comment]
Thanks for opening this. I will implement these commands once HASH commands are done (probably will start looking at it next week)

**Comment by sabledb-io** [comment]
@trkohler you opened 3 issues for 3 missing commands, but I doubt that this is all the commands you are using.

`ZADD`, `ZCARD` and `ZINCRBY` perform updates / insert and `ZCARD` returns the size of the set.
What about reading the member / scores? commands like `ZSCORE` or `ZRANGE` etc (something that allows you to query the set members)

**Comment by trkohler** [comment]
Hello! I've just got news that it was decided to choose valkey for a project I was looking for redis alternative. The project itself written in Go and the project team needs to have ring client in Go as well, where everyone would be able to read / contribute. 

I was hoping we could give a shot to sabledb, but now understand I wouldn't be able to influence the decision. Because of those reasons I won't open new issues with requests unless I will find another opportunity where sabledb can be tried. I will continue to support and follow sabledb development and thank you very much for working on it!

**Comment by sabledb-io** [comment]
Sure, np  😄 
FYI: `valkey` main maintainer is a good friends of mine - so you are making a good choice here
