### ISSUE TITLE
Some key may not evict

### ISSUE THREAD

**Issue by WillsonYip** [sabledb-io/sabledb#22]
in cron_thread.rs.  `fn record_exists` decide the key is valid or not.  here is the code.

```rust
    fn record_exists(
        store: &StorageAdapter,
        record: &Bookkeeping,
        user_key: &BytesMut,
        expected_value_type: &ValueType,
    ) -> Result<RecordExistsResult, SableError> {
        let mut generic_db = GenericDb::with_storage(store, record.db_id());
        let md = generic_db.value_common_metadata(user_key)?;
        match md {
            Some(md) => Ok(if md.value_type().eq(expected_value_type) {
                RecordExistsResult::Found
            } else {
                tracing::info!(
                    "'{:?}' found but with wrong type. Expected {:?}, Found: {:?}",
                    user_key,
                    expected_value_type,
                    md.value_type()
                );
                RecordExistsResult::WrongType
            }),
            None => Ok(RecordExistsResult::NotFound),
        }
    }
```

`md.value_type().eq(expected_value_type)`  is true.  but  `md.uid() == record.uid()` maybe be false in which case some orphan key may be ignored.   

But sad story, I can't find any real case .   so I'm not quite sure this is intended or some bug.

**Comment by sabledb-io** [comment]
Good catch.

The use case you are describing can happen in commands where the API allows overriding an existing key with the same *type*. An example for such command is [`SINTERSTORE`](https://redis.io/docs/latest/commands/sinterstore/)

In this command, if the destination *exists* it is overridden. so imagine the following:

```
set1(uid=1234) => {1, 2, 3, 4}
set2(uid=1235) => {1, 2, 5, 6}
set3(uid=1236) => {10, 11}
```

Running `SINTERSTORE set3 set1 set2` will override the existing set `set3`, so the check `md.value_type().eq(expecectd_value_type)` is `true` but they now have different UID.
