### ISSUE TITLE
Support for hashes, sets, and sorted sets

### ISSUE THREAD

**Issue by alanhamlett** [sabledb-io/sabledb#7]
Please support [hash commands](https://redis.io/docs/data-types/hashes/), [sorted sets](https://redis.io/docs/data-types/sorted-sets/), and [sets](https://redis.io/docs/data-types/sets/). I personally use hashes more than lists in my apps, and would be nice to have an alternative to [ssdb](https://github.com/ideawu/ssdb) since that project has stalled.

**Comment by alanhamlett** [comment]
I use sorted sets and sets in my [background task queue library](https://github.com/wakatime/wakaq) but I also use `SCRIPT LOAD` for wrapping multiple commands into transactions, so let's ignore that use case as it's out of scope.

For application-only code, I only use `GET`, `SETX`, `SET`, `EXPIRE`, `DELETE`, `INCR`, `HGET`, `HSET`, `HDEL`, `HLEN`, `LPOP`, `RPUSH`, `LRANGE`, `LLEN`, `INCRBY`, `EXISTS`.

**Comment by sabledb-io** [comment]
Thanks for taking the time and prioritize the missing commands.
So, we are missing:

`EXPIRE`, `HGET`, `HSET`, `HDEL`, `HLEN`, `EXISTS`

Commands?

Also, I don't think redis has this command: `DELETE`, it does has `DEL`
Am I missing something?

**Comment by alanhamlett** [comment]
Fixed. One of my client libraries uses the delete command in their API but actually calls del.

**Comment by 0del** [comment]
>So, we are missing:
EXPIRE, HGET, HSET, HDEL, HLEN, EXISTS

@sabledb-io can i work on it ?

**Comment by 0del** [comment]
Okey, 
One more thing, If you can guide me to implement `EXPIRE` command, I really happy to help you @sabledb-io

**Comment by sabledb-io** [comment]
@0del I just added support to `EXISTS` command. You might want to see the commit, it basically contains everything you need in order to add a command to `SableDb`

https://github.com/sabledb-io/sabledb/commit/0b6e6d875131da752598f22c076624c93228091f

**Comment by 0del** [comment]
okey, thanks for your supports
I will add these (HGET, HSET, HDEL, HLEN, EXISTS) commands
I am going to create many pull requests to split the big changes, hope you will be fine to review them @sabledb-io

**Comment by sabledb-io** [comment]
Ofc, note that I have started adding support for encoding `HASH` keys in the database - this is something that is currently missing and I am working on.

Here is sketch that I am working with that might clear up what I mean by: "encoded keys":

![SableDb_Database_Layout excalidraw](https://github.com/sabledb-io/sabledb/assets/165516376/12e36da7-4910-4f0f-815d-6e66542f4c3e)

**Comment by sabledb-io** [comment]
@0del I added `hash_db` which allows you to manipulate hash / hash field in the storage. See the unit tests to see how to use it.
https://github.com/sabledb-io/sabledb/blob/main/libsabledb/src/storage/hash_db.rs#L313

**Comment by sabledb-io** [comment]
@alanhamlett FYI: `hset` + `hget` are implemented

https://github.com/sabledb-io/sabledb/commit/f18d8da7b2c36e3c913b8955c96340e68861f2f4

**Comment by sabledb-io** [comment]
@alanhamlett I think we can close this, as most the commands you mentioned where all added https://github.com/sabledb-io/sabledb/issues/7#issuecomment-2039645201

If you are missing some more specific commands, please open an issue per command
